### PR TITLE
Make ShowUpDownButton public instead of private

### PR DESCRIPTION
**Pull request by AlphaNecron**
Please merge this PR and release a new Nuget version please...
Check your codes btw

### CODE REVIEW

**Comment by ghost1372** [comment]
Some code is intentionally internal
I made some of them public in https://github.com/ghost1372/HandyControls/commit/c989576a016066dfc803b1af32af2f7a49bfebee
Sorry about that but I just updated the nuget 2 days ago and I can not update the nuget just because of this pr (At the moment We do not have any other changes such as bug fixes or new features)
I think the next version will be released in the next month

**Comment by AlphaNecron** [comment]
Is there anyway to build this?

**Comment by AlphaNecron** [comment]
It shouldn't be either `private` or `internal`  because it would be hard to make custom controls...

**Comment by ghost1372** [comment]
You can build it yourself
https://hosseini.ninja/handycontrol/#Compile-source-code

**Comment by AlphaNecron** [comment]
ty

**Pull request merged**
